# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"AutoTS": "core.ipynb"}

modules = ["core.py"]

doc_url = "https://Nixtla.github.io/autotimeseries/"

git_url = "https://github.com/Nixtla/nixtla/tree/main/sdk/python-autotimeseries"

def custom_doc_links(name): return None
