repos:
  - repo: local
    hooks:
      - id: nbdev_clean
        name: Clean notebooks
        entry: sh -c 'nbdev_clean && nbdev_clean --fname nbs/src --clear_all'
        language: system

  - repo: local
    hooks:
      - id: nbdev_export
        name: nbdev_export
        entry: sh -c 'nbdev_export'
        language: system

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        files: 'nixtla'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        files: 'nixtla'
