name: nixtla
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cpuonly
  - pandas
  - pip
  - pytorch
  - requests
  - tqdm
  - xlrd
  - pip:
    - nbdev
    - tabulate
