name: nixtla
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - hyperopt
  - matplotlib
  - pandas
  - pip
  - requests
  - statsmodels
  - scikit-learn
  - tqdm
  - xlrd
  - pip:
    - nbdev
    - tabulate
    - python-dotenv
    - fsspec
    - s3fs
