name: nixtla
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pandas
  - pip
  - pytorch
  - requests
  - tqdm
  - xlrd
  - pip:
    - nbdev
    - tabulate
    - python-dotenv
    - fsspec
    - s3fs
