# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"uids_ts_from_df": "dataloaders.ipynb",
         "NBeatsDataLoader": "dataloaders.ipynb",
         "SOURCE_URL": "datasets.ipynb",
         "logger": "datasets.ipynb",
         "download_file": "datasets.ipynb",
         "TimeSeriesDataset": "datasets.ipynb",
         "Yearly": "datasets.ipynb",
         "Quarterly": "datasets.ipynb",
         "Monthly": "datasets.ipynb",
         "TourismInfo": "datasets.ipynb",
         "Tourism": "datasets.ipynb"}

modules = ["data/dataloaders.py",
           "data/datasets.py"]

doc_url = "https://Grupo-Abraxas.github.io/nixtla/"

git_url = "https://github.com/Grupo-Abraxas/nixtla/tree/master/"

def custom_doc_links(name): return None
